# Python GitHub Actions Workflow
name: Python CI

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  test:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'developer'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        cd python
        pip install -r requirements.txt

    - name: Run Python Tests
      run: |
        cd python
        python -m unittest discover tests